src/Entity/Region.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RegionRepository")
 */
class Region
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\City", mappedBy="region")
     */
    private $cities;

    public function __construct()
    {
        $this->cities = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|City[]
     */
    public function getCities(): Collection
    {
        return $this->cities;
    }

    public function addCity(City $city): self
    {
        if (!$this->cities->contains($city)) {
            $this->cities[] = $city;
            $city->setRegion($this);
        }

        return $this;
    }

    public function removeCity(City $city): self
    {
        if ($this->cities->contains($city)) {
            $this->cities->removeElement($city);
            // set the owning side to null (unless already changed)
            if ($city->getRegion() === $this) {
                $city->setRegion(null);
            }
        }

        return $this;
    }

    public function getMainCities()
    {
        $criteria = new Criteria();
        $criteria->andWhere(Criteria::expr()->eq('village', false));
        $criteria->orderBy(['name'=>'asc']);

        return $this->cities->matching($criteria);
    }

    public function getRegionCenter()
    {
        $criteria = new Criteria();
        $criteria->orderBy(['lat'=>'asc']);
        $criteria->setMaxResults(1);
        $minLat = $this->cities->matching($criteria)->first()->getLat();
        $criteria = new Criteria();
        $criteria->orderBy(['lon'=>'asc']);
        $criteria->setMaxResults(1);
        $minLon = $this->cities->matching($criteria)->first()->getLon();
        $criteria = new Criteria();
        $criteria->orderBy(['lat'=>'desc']);
        $criteria->setMaxResults(1);
        $maxLat = $this->cities->matching($criteria)->first()->getLat();
        $criteria->orderBy(['lon'=>'desc']);
        $criteria->setMaxResults(1);
        $maxLon = $this->cities->matching($criteria)->first()->getLon();

        return [($maxLat+$minLat)/2,($maxLon+$minLon)/2];
    }
}

src/Form/FlatType.php
<?php

namespace App\Form;

use App\Entity\BathroomType;
use App\Entity\BuildingType;
use App\Entity\City;
use App\Entity\Equipment;
use App\Entity\Flat;
use App\Entity\FlatPreference;
use App\Entity\FurnitureType;
use App\Entity\HeatingType;
use App\Entity\KitchenType;
use App\Entity\WindowsType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Tetranz\Select2EntityBundle\Form\Type\Select2EntityType;

class FlatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',TextType::class,[
                'label' => 'Tytuł ogłoszenia'
            ])
            ->add('description', TextareaType::class,[
                'label' => 'Opis dodatkowy'
            ])
            ->add('latitude')
            ->add('longitude')
            ->add('area', NumberType::class, [
                'label' => 'Metraż',
                'scale' => 2,
                'required' => false
            ])
            ->add('floor', IntegerType::class,[
                'label' => 'Piętro',
                'required' => false
            ])
            ->add('constructionYear', IntegerType::class,[
                'label' => 'Rok budowy budynku',
                'required' => false
            ])
            ->add('floors', IntegerType::class,[
                'label' => 'Ilość pięter w budynku',
                'required' => false
            ])
            ->add('freeFrom', DateType::class, [
                'label' => 'Wolne od',
                'required' => false,
                'widget' => 'single_text'
            ])
            ->add('internet', CheckboxType::class,[
                'label' => 'Internet',
                'required' => false
            ])
            ->add('internetBandwidth', IntegerType::class, [
                'label' => 'Przepustowość internetu (mbit/s)',
                'required' => false
            ])
            ->add('firstName', TextType::class,[
                'label' => 'Imię do kontaktu',
                'required' => false
            ])
            ->add('email')
            ->add('phone1', TextType::class, [
                'label' => 'Pierwszy telefon kontaktowy'
            ])
            ->add('phone2', TextType::class, [
                'label' => 'Drugi telefon kontaktowy',
                'required' => false
            ])
            ->add('flatType', EntityType::class, [
                'class' => \App\Entity\FlatType::class,
                'label' => 'Typ ogłoszenia',
            ])
            ->add('buildingType', EntityType::class, [
                'class' => BuildingType::class,
                'label' => 'Typ budynku',
                'required' => false
            ])
            ->add('furnishings', EntityType::class, [
                'class' => FurnitureType::class,
                'label' => 'Umeblowanie',
                'required' => false
            ])
            ->add('heatingType', EntityType::class, [
                'class' => HeatingType::class,
                'label' => 'Ogrzewanie',
                'required' => false
            ])
            ->add('kitchenType', EntityType::class, [
                'class' => KitchenType::class,
                'label' => 'Kuchnia',
                'required' => false
            ])
            ->add('bathroomType', EntityType::class, [
                'class' => BathroomType::class,
                'label' => 'Łazienka',
                'required' => false
            ])
            ->add('windowsType', EntityType::class, [
                'class' => WindowsType::class,
                'label' => 'Okna',
                'required' => false
            ])
            ->add('equipment', EntityType::class, [
                'class' => Equipment::class,
                'label' => 'Wposażenie',
                'required' => false,
                'multiple' => true,
                'expanded' => true
            ])
            ->add('preferences', EntityType::class, [
                'class' => FlatPreference::class,
                'label' => 'Preferuję',
                'required' => false,
                'multiple' => true,
                'expanded' => true
            ])
            ->add('rooms', CollectionType::class, [
                'entry_type' => RoomType::class,
                'allow_add' => true,
                'prototype' => true
            ])
            ->add('city', Select2EntityType::class,[
                'remote_route' => 'api_city_search',
                'class' => City::class,
                'required' => true
            ])
            ->add('address')
            ->add('photos', CollectionType::class,[
                'allow_add' => true,
                'allow_delete' => true
            ])
            ->add('price', IntegerType::class,[
                'required' => false,
                'attr' => ['min'=>1,'max'=>1000000],
                'label' => 'Cena (zł)'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Flat::class,
        ]);
    }
}

src/Controller/FlatController.php
<?php

namespace App\Controller;

use App\Entity\BathroomType;
use App\Entity\BuildingType;
use App\Entity\City;
use App\Entity\Flat;
use App\Entity\HeatingType;
use App\Entity\KitchenType;
use App\Entity\Region;
use App\Entity\WindowsType;
use App\Form\FlatType;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\GreaterThan;
use Symfony\Component\Validator\Constraints\LessThan;

/**
 * @Route("/ogloszenia")
 */
class FlatController extends AbstractController
{
    private $objectManager;
    private $paginator;

    public function __construct(ObjectManager $objectManager, PaginatorInterface $paginator)
    {
        $this->objectManager = $objectManager;
        $this->paginator = $paginator;
    }

    /**
     * @Route("/dodaj-nowe", name="flat_create")
     * @IsGranted("ROLE_USER")
     */
    public function addNew(Request $request)
    {
        $flat = new Flat();
        $flat->setUser($this->getUser());
        $form = $this->createForm(FlatType::class, $flat);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            foreach ($flat->getRooms() as $room)
                $room->setFlat($flat);

            $this->objectManager->persist($flat);
            $this->objectManager->flush();

            return $this->redirectToRoute('homepage');
        }

        return $this->render('flat/new.html.twig',[
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/pokaz/{slug<[a-z0-9\-]+>}-{flat}", name="flat_show")
     */
    public function show(Flat $flat, $slug)
    {
        if($flat->getSlug() != $slug)
            return $this->redirectToRoute('flat_show',[
                'slug' => $flat->getSlug(),
                'id'=> $flat->getId()
            ]);

        return $this->render('flat/flat.html.twig',[
            'flat' => $flat
        ]);
    }

    /**
     * @Route("/", name="flats_listing")
     * @Route("/{regionSlug}", name="flats_listing_region")
     * @Route("/{regionSlug}/{citySlug}", name="flats_listing_region_city")
     */
    public function listing($regionSlug=null,$citySlug=null, Request $request)
    {
        $region = null;
        if($regionSlug!==null)
        {
            $region = $this->objectManager->getRepository(Region::class)->findOneBy(['slug'=>$regionSlug]);
            if(!$region)
                throw new NotFoundHttpException();
        }

        $city = null;
        if($citySlug!==null)
        {
            $city = $this->objectManager->getRepository(City::class)->findOneBy(['region'=>$region,'slug'=>$citySlug]);
            if(!$city)
                throw new NotFoundHttpException();
        }

        $filters = $this->get('form.factory')->createNamedBuilder('filters', FormType::class, [
            'csrf_protection' => null
        ])
            ->setMethod('get')
            ->add('flatType', EntityType::class,[
                'class' => \App\Entity\FlatType::class,
                'label' => 'Typ ogłoszenia',
                'multiple' => true,
                'expanded' => true,
                'required' => false
            ])
            ->add('buildingType', EntityType::class,[
                'class' => BuildingType::class,
                'label' => 'Typ budynku',
                'multiple' => true,
                'expanded' => true,
                'required' => false
            ])
            ->add('heatingType', EntityType::class,[
                'class' => HeatingType::class,
                'label' => 'Typ ogrzewania',
                'multiple' => true,
                'expanded' => true,
                'required' => false
            ])
            ->add('kitchenType', EntityType::class,[
                'class' => KitchenType::class,
                'label' => 'Typ kuchni',
                'multiple' => true,
                'expanded' => true,
                'required' => false
            ])
            ->add('bathroomType', EntityType::class,[
                'class' => BathroomType::class,
                'label' => 'Typ łazienki',
                'multiple' => true,
                'expanded' => true,
                'required' => false
            ])
            ->add('windowsType', EntityType::class,[
                'class' => WindowsType::class,
                'label' => 'Typ okien',
                'multiple' => true,
                'expanded' => true,
                'required' => false
            ])
            ->add('priceFrom', IntegerType::class, [
                'required' => false,
                'label' => 'Cena od',
                'attr' => ['min'=>1,'max'=>1000000],
            ])
            ->add('priceTo', IntegerType::class, [
                'required' => false,
                'label' => 'Cena do',
                'attr' => ['min'=>1,'max'=>1000000],
            ])
            ->getForm();
        $filters->handleRequest($request);
        $filtersArr = [];
        if($filters->isSubmitted() && $filters->isValid())
        {
            $data = $filters->getData();
            if($data['priceFrom'] != null) $filtersArr['priceFrom'] = $data['priceFrom'];
            if($data['priceTo'] != null) $filtersArr['priceTo'] = $data['priceTo'];
            if(count($data['flatType']) > 0) $filtersArr['flatType'] = $data['flatType'];
            if(count($data['buildingType']) > 0) $filtersArr['buildingType'] = $data['buildingType'];
            if(count($data['heatingType']) > 0) $filtersArr['heatingType'] = $data['heatingType'];
            if(count($data['kitchenType']) > 0) $filtersArr['kitchenType'] = $data['kitchenType'];
            if(count($data['windowsType']) > 0) $filtersArr['windowsType'] = $data['windowsType'];
        }

        $distanceFilter = $this->get('form.factory')->createNamedBuilder('d', FormType::class, [
            'csrf_protection' => null
        ])
            ->setMethod('get')
            ->add('lat',HiddenType::class, [
                'constraints' => [
                    new GreaterThan(['value'=>48]),
                    new LessThan(['value'=>55])
                ]
            ])
            ->add('lon', HiddenType::class, [
                'constraints' => [
                    new GreaterThan(['value'=>14]),
                    new LessThan(['value'=>24])
                ]
            ])
            ->add('dist', ChoiceType::class, [
                'label' => 'Szukaj w promieniu',
                'choices' => [
                    '1 km' => 1,
                    '5 km' => 5,
                    '10 km' => 10,
                    '20 km' => 20,
                    '30 km' => 30,
                    '40 km' => 40,
                    '50 km' => 50
                ]
            ])
            ->getForm();
        $distanceFilter->handleRequest($request);

        $distanceArr = [];
        if($distanceFilter->isSubmitted() && $distanceFilter->isValid())
        {
            $data = $distanceFilter->getData();
            if($data['dist'] != null && $data['lat'] != null && $data['lon'])
                $distanceArr = [
                    'dist' => $data['dist'],
                    'lat' => $data['lat'],
                    'lon' => $data['lon']
                ];
        }

        $flats = $this->objectManager->getRepository(Flat::class)->search(array_merge([
            'region' => $region,
            'city' => $city,
        ], $filtersArr, $distanceArr));
        /**
         * @var Flat[] $pagination
         */
        $pagination = $this->paginator->paginate(
            $flats,
            $request->query->getInt('p',1),
            10
        );

        return $this->render('flat/listing.html.twig',[
            'flats' => $pagination,
            'region' => $region,
            'regions' => $this->objectManager->getRepository(Region::class)->findBy([],['name'=>'asc']),
            'city' => $city,
            'filters' => $filters->createView(),
            'distanceFilter' => $distanceFilter->createView()
        ]);
    }
}

templates/flat/listing.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Dostępne ogłoszenia
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div id="filters" class="collapse">
                    <h3>Filtry</h3>
                    <div class="card">
                        <div class="card-body">

                            {{ form_start(filters) }}
                            <div class="row">
                                <div class="col-sm-4">{{ form_row(filters.flatType) }}</div>
                                <div class="col-sm-4">{{ form_row(filters.buildingType) }}</div>
                                <div class="col-sm-4">{{ form_row(filters.heatingType) }}</div>
                                <div class="col-sm-4">{{ form_row(filters.kitchenType) }}</div>
                                <div class="col-sm-4">{{ form_row(filters.bathroomType) }}</div>
                                <div class="col-sm-4">{{ form_row(filters.windowsType) }}</div>
                                <div class="col-sm-4">{{ form_row(filters.priceFrom) }}</div>
                                <div class="col-sm-4">{{ form_row(filters.priceTo) }}</div>
                                <div class="col-sm-4 text-right"><button type="submit" class="btn btn-success"><i class="fas fa-search"></i> Szukaj</button></div>
                            </div>
                            {{ form_end(filters) }}
                        </div>
                    </div>
                </div>
                <button type="button" class="btn btn-success btn-sm float-right" data-toggle="collapse" data-target="#filters"><i class="fas fa-filter"></i> Filtry</button>
                <h2>Lista ogłoszeń</h2>
                {% for flat in flats %}
                    <div class="row">
                        <div class="col-3">
                            <img src="{{ flat.firstPhotoPath }}" class="img-fluid" alt="{{ flat.title }}">
                        </div>
                        <div class="col-9">
                            <span class="float-right text-right">
                                <i class="far fa-clock"></i> {{ flat.createdAtDiff }}<br>
                                <i class="fas fa-map-marker"></i> {{ flat.city.name }}, {{ flat.city.district.name }}, {{ flat.city.region.name }}
                            </span>
                            <h4><a href="{{ path('flat_show', {'flat': flat.id, 'slug': flat.slug}) }}">{{ flat.title }}</a></h4>
                        </div>
                    </div>
                    <hr>
                {% else %}
                    <div class="alert">Brak ogłoszeń</div>
                {% endfor %}
                {{ knp_pagination_render(flats) }}
            </div>
            <div class="col-md-3">
                <button type="button" class="btn btn-primary w-100" data-toggle="modal" data-target="#mapModal">Szukaj ogłoszeń w promieniu</button>
                <h2>Lokalizacja:</h2>
                <div class="list-group">
                    <a href="{{ path('flats_listing') }}" class="list-group-item list-group-item-action {{ region is null ? 'active' }} py-1">Cała Polska</a>
                {% for r in regions %}
                        <a href="{{ path('flats_listing_region', {'regionSlug': r.slug}) }}" class="list-group-item list-group-item-action {{ r == region ? 'active' }} py-1">{{ r.name }}</a>
                        {% if r == region %}
                            <div class="list-group-item">
                                {% for c in region.mainCities %}
                                    <div>
                                        <a href="{{ path('flats_listing_region_city', {'citySlug': c.slug, 'regionSlug': r.slug}) }}" class="{{ city == c ? 'font-weight-bold text-secondary' }}">{{ c.name }}</a>
                                    </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="modal" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="mapModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="mapModalLabel">Szukaj ogłoszeń w promieniu</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ form_start(distanceFilter) }}
                    <div class="embed-responsive embed-responsive-4by3">
                        <div id="map" class="embed-responsive-item"></div>
                    </div>
                    {{ form_row(distanceFilter.dist) }}
                    <button type="button" class="btn btn-danger" id="deleteMarker"><i class="fas fa-times"></i> Usuń znacznik</button>
                    <button type="submit" class="btn btn-success"><i class="fas fa-search"></i> Szukaj</button>
                    {{ form_end(distanceFilter) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script type="text/javascript">
        var marker = null;
        map = L.map('map').setView([52.0691,19.48], 6);
        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            maxZoom: 18,
            id: 'mapbox.streets',
            accessToken: 'pk.eyJ1IjoidmljdXJlbCIsImEiOiJjams5c3Z6ZjUxenF4M3FxbG5reTVsOHF1In0.9YrR4IU3rxQSNuWGwQz_HQ'
        }).addTo(map);

        {% if region %}
            {% set center = region.regionCenter %}
            map.setView([{{ center[0] }},{{ center[1] }}], 8);
        {% endif %}


        {% if distanceFilter.vars.submitted and distanceFilter.vars.valid and distanceFilter.lat.vars.value %}
            marker = L.marker([{{ distanceFilter.lat.vars.value }}, {{ distanceFilter.lon.vars.value }}]).addTo(map);
        {% endif %}

        map.on('click',function (e) {
            if(marker)
                map.removeLayer(marker);

            marker = L.marker([e.latlng.lat, e.latlng.lng]).addTo(map);
            $('#d_lat').val(e.latlng.lat);
            $('#d_lon').val(e.latlng.lng);
        });

        $('#deleteMarker').click(function () {
            if(marker)
                map.removeLayer(marker);
            $('#d_lat').val('');
            $('#d_lon').val('');
            $('#d_lat').closest('form').submit();
        });

        $('#mapModal').on('shown.bs.modal', function () {
            map.invalidateSize();
        });
    </script>
{% endblock %}

templates/flat/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'partials/flat-form.html.twig' with {'form': form}%}
{% endblock %}